apiVersion: v1
kind: Secret
metadata:
  name: example-postgres-secrets
  labels:
    app: example-app
type: Opaque
data:
  postgres_username: dXNlcm5hbWU=  # Root Username: echo -n "username" | base64
  postgres_password: cGFzc3dvcmQ=  # Root Password: echo -n "password" | base64
  gcp_service_account.json: enter_your_base64_encoded_service_account_json_key_here
